services:
  app:
    container_name: golang-auth
    build:
      dockerfile: ./docker/dev/Dockerfile
    command: air
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    volumes:
      - ".:/app"
    networks:
      - default
    depends_on:
      - postgres

  adminer:
    container_name: golang-auth-adminer
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - default
    depends_on:
      - postgres

  postgres:
    container_name: golang-auth-db
    image: postgres:alpine
    restart: always
    volumes:
      - "postgres-db:/var/lib/postgresql/data"
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres-db: