name: Go CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.1'

    - name: Install Dependencies
      run: go mod tidy

    - name: Test
      run: go test -v ./tests/...

    - name: Build
      run: go build -v ./cmd/main.go